name: portfolio_website
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Flutter common packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  websafe_svg: ^3.0.1+10
  flutter_riverpod: ^2.6.1
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  gap: ^3.0.1

  # UI / Layout
  dotted_line: ^3.2.3
  flutter_staggered_grid_view: ^0.7.0
  visibility_detector: ^0.4.0+2

  # Routing / Networking
  go_router: ^17.0.0
  dio: ^5.9.0
  url_launcher: ^6.3.2

  # SEO
  seo: ^0.0.10

  # Linting & Code Generation
  flutter_lints: ^5.0.0
  custom_lint: 0.7.6
  riverpod_lint: ^2.3.12
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4

  # Flutter web plugins....
  flutter_web_plugins:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true





  assets:
    - assets/
    - assets/icons/
    - assets/icon/
    - assets/fonts/
    - assets/images/
    - assets/icons/profile.jpg

  fonts:
    - family: Typewriter
      fonts:
        - asset: assets/fonts/Typedeer Mono Demo.ttf
          weight: 700
    - family: Italics
      fonts:
        - asset: assets/fonts/Andina Demo.otf
          weight: 700
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
          weight: 700
    - family: Sora-Regular
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
          weight: 400
    - family: Sora-Bold
      fonts:
        - asset: assets/fonts/Sora-Bold.ttf
          weight: 700
    - family: Sora-SemiBold
      fonts:
        - asset: assets/fonts/Sora-SemiBold.ttf
          weight: 700
    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
          weight: 700


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/app_icon.png
  min_sdk_android: 21 # android min sdk min:16, default 21.....
  web:
    generate: true
    image_path: assets/icons/app_icon.png
    background_color: "#5D0B48"
    theme_color: "#5D0B48"